#Configurations for material Void.
[general]
	#The module blacklist of this material.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The color of this material.
	color = 1838639
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "metallic"
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
[avaritia]
	#Should the singularity be added to the Infinity Catalyst recipe.
	addToCatalyst = true
	#The base amount of blocks required to create one singularity.
	inputAmount = 300
[avaritia_singularity]
	#Should the singularity be added to the Infinity Catalyst recipe.
	addToCatalyst = true
	#The base amount of blocks required to create one singularity.
	inputAmount = 300
