
mods.extendedcrafting.TableCrafting.addShaped(4, <auraddons:item_creative_aura_cache>, [
	[null, null, null, <auraddons:block_aura_transporter>, <auraddons:block_aura_transporter>, <auraddons:block_aura_transporter>, null, null, null], 
	[null, null, <auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:aura_detector>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>, null, null], 
	[null, <auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:field_creator>, <naturesaura:field_creator>, <naturesaura:field_creator>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>, null], 
	[<auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:field_creator>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:field_creator>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>], 
	[<auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:field_creator>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:field_creator>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>], 
	[<auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:field_creator>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:field_creator>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>], 
	[null, <auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:field_creator>, <naturesaura:field_creator>, <naturesaura:field_creator>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>, null], 
	[null, null, <auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:aura_detector>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>, null, null], 
	[null, null, null, <auraddons:block_aura_transporter>, <auraddons:block_aura_transporter>, <auraddons:block_aura_transporter>, null, null, null]
]);
mods.extendedcrafting.TableCrafting.addShaped(4, <bloodmagic:activation_crystal:2>, [
	[<bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <ore:blockBloodInfusedIron>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <ore:blockBloodInfusedIron>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <ore:blockBloodInfusedIron>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <botania:enderdagger>, <botania:enderdagger>, <botania:enderdagger>, <ore:blockBloodInfusedIron>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <botania:enderdagger>, <botania:enderdagger>, <botania:enderdagger>, <ore:blockBloodInfusedIron>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <botania:enderdagger>, <botania:enderdagger>, <botania:enderdagger>, <ore:blockBloodInfusedIron>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>]
]);

mods.extendedcrafting.TableCrafting.addShaped(4, <tinkertoolcasts:cast_creative>, [
	[<ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:1>, <tinkertoolcasts:cast_ultimate:1>, <tinkertoolcasts:cast_ultimate:1>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate:2>, <tinkertoolcasts:cast_ultimate:2>, <tinkertoolcasts:cast_ultimate:2>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:1>, <tinkertoolcasts:upgrade_advanced>, <tinkertoolcasts:upgrade_advanced>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:upgrade_reinforced>, <tinkertoolcasts:upgrade_reinforced>, <tinkertoolcasts:cast_ultimate:2>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:1>, <tinkertoolcasts:upgrade_advanced>, <tinkertoolcasts:upgrade_advanced>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:upgrade_reinforced>, <tinkertoolcasts:upgrade_reinforced>, <tinkertoolcasts:cast_ultimate:2>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:3>, <tinkertoolcasts:upgrade_iridium>, <tinkertoolcasts:upgrade_iridium>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:upgrade_ultimate>, <tinkertoolcasts:upgrade_ultimate>, <tinkertoolcasts:cast_ultimate:4>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:3>, <tinkertoolcasts:upgrade_iridium>, <tinkertoolcasts:upgrade_iridium>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:upgrade_ultimate>, <tinkertoolcasts:upgrade_ultimate>, <tinkertoolcasts:cast_ultimate:4>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:3>, <tinkertoolcasts:cast_ultimate:3>, <tinkertoolcasts:cast_ultimate:3>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate:4>, <tinkertoolcasts:cast_ultimate:4>, <tinkertoolcasts:cast_ultimate:4>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>]
]);

mods.extendedcrafting.TableCrafting.addShaped(4, <thaumicwonders:creative_essentia_jar>, [
	[<thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumicenergistics:essentia_component_64k>, <thaumicrestoration:block_crystal>, <avaritia:resource:5>, <thaumicrestoration:block_crystal>, <thaumicenergistics:essentia_component_64k>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumicenergistics:essentia_component_64k>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <thaumicenergistics:essentia_component_64k>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumicenergistics:essentia_component_64k>, <thaumicrestoration:block_crystal>, <avaritia:resource:5>, <thaumicrestoration:block_crystal>, <thaumicenergistics:essentia_component_64k>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>]
]);

mods.extendedcrafting.TableCrafting.addShaped(4, <wct:wct_creative>, [
	[<ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wct:wct>, <wct:wct>, <wct:wct>, <wct:magnet_card>, <wft:wft>, <wft:wft>, <wft:wft>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wct:wct>, <wct:wct>, <wct:wct>, <wct:magnet_card>, <wft:wft>, <wft:wft>, <wft:wft>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wct:wct>, <wct:wct>, <wct:wct>, <wct:magnet_card>, <wft:wft>, <wft:wft>, <wft:wft>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wct:magnet_card>, <wct:magnet_card>, <wct:magnet_card>, <wct:magnet_card>, <wct:magnet_card>, <wct:magnet_card>, <wct:magnet_card>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wit:wit>, <wit:wit>, <wit:wit>, <wct:magnet_card>, <wpt:wpt>, <wpt:wpt>, <wpt:wpt>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wit:wit>, <wit:wit>, <wit:wit>, <wct:magnet_card>, <wpt:wpt>, <wpt:wpt>, <wpt:wpt>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wit:wit>, <wit:wit>, <wit:wit>, <wct:magnet_card>, <wpt:wpt>, <wpt:wpt>, <wpt:wpt>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>]
]);

mods.extendedcrafting.TableCrafting.addShaped(4, <reactorbuilder:creativereactorbuilder>, [
	[<nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_glass>, <draconicevolution:reactor_component>, <draconicevolution:reactor_component>, <draconicevolution:reactor_component>, <nuclearcraft:fission_glass>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_glass>, <draconicevolution:reactor_component>, <draconicadditions:chaos_stabilizer_core>, <draconicevolution:reactor_component>, <nuclearcraft:fission_glass>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_glass>, <draconicevolution:reactor_component>, <draconicevolution:reactor_component>, <draconicevolution:reactor_component>, <nuclearcraft:fission_glass>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>]
]);

mods.extendedcrafting.TableCrafting.addShaped(4, <equivalentenergistics:emc_cell_creative>, [
	[<ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_crafter:3>, <equivalentenergistics:emc_crafter:3>, <equivalentenergistics:emc_crafter:3>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_crafter:3>, <equivalentenergistics:emc_crafter:3>, <equivalentenergistics:emc_crafter:3>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_condenser:3>, <equivalentenergistics:emc_condenser:3>, <equivalentenergistics:emc_condenser:3>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_condenser:3>, <equivalentenergistics:emc_condenser:3>, <equivalentenergistics:emc_condenser:3>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>]
]);

mods.extendedcrafting.TableCrafting.addShapeless(4, <contenttweaker:ultimate_ingot_left_up>, [<ore:ingotThorium>, <ore:ingotGraphite>, <ore:ingotBeryllium>, <ore:ingotTin>, <ore:ingotPsioMetal>, <ore:ingotLead>, <ore:ingotAluminum>, <ore:ingotNickel>, <ore:ingotOsmium>, <ore:ingotDarkChocolate>, <ore:ingotCocoaButter>, <ore:ingotSoulium>, <naturesaura:infused_iron>, <ore:ingotShibuichi>, <ore:ingotLeadPlatinum>, <ore:ingotZinc>, <ore:ingotElectricium>, <ore:ingotSkyfather>, <ore:ingotEnergium>, <ore:ingotEvilMetal>, <ore:ingotPlatinum>, <ore:ingotVibrantAlloy>, <ore:ingotTinSilver>, <ore:ingotCopper>, <ore:ingotAlchemicalBrass>, <ore:ingotManganese>, <ore:ingotZirconium>, <ore:ingotIron>, <ore:ingotGold>, <ore:ingotLithium>, <ore:ingotBoron>, <ore:ingotElvenElementium>, <ore:ingotIntermedium>, <ore:ingotBaseEssence>, <ore:ingotSky>, <ore:ingotMagnesium>, <ore:ingotEnergeticAlloy>, <ore:ingotConductiveIron>, <ore:ingotEnergeticSilver>, <ore:ingotCrystallineAlloy>, <ore:ingotStellarAlloy>, <ore:ingotUnstable>, <ore:ingotDemonicMetal>, <ore:ingotAdvancedElectronicAlloy>, <ore:ingotVividAlloy>, <ore:ingotFluixSteel>, <ore:ingotPinkMetal>, <ore:ingotSilicon>, <ore:ingotPulsatingIron>, <ore:ingotSoularium>, <ore:ingotBlackIron>, <ore:ingotManganeseDioxide>, <ore:ingotMithril>, <ore:ingotCold>, <ore:ingotUranium>, <ore:ingotFerroboron>, <ore:ingotInferium>, <ore:ingotPrudentium>, <ore:ingotSuperium>, <ore:ingotSiCSiCCMC>, <ore:ingotNickel>, <ore:foodChocolatebar>, <ore:ingotMarshmallow>, <ore:ingotOsmiridium>, <ore:ingotAdvancedAlloy>, <ore:ingotThaumium>, <ore:ingotZinc>, <ore:ingotCobalt>, <ore:ingotIronwood>, <ore:ingotFiery>, <ore:ingotThaumiumPerditio>, <ore:ingotThaumiumIgnis>, <ore:ingotThaumiumAer>, <ore:ingotThaumiumOrdo>, <ore:ingotThaumiumAqua>, <ore:ingotIridium>, <ore:ingotEnderium>, <ore:ingotLumium>, <ore:ingotConstantan>, <ore:ingotElectrum>, <ore:ingotSteel>]);
mods.extendedcrafting.TableCrafting.addShapeless(4, <contenttweaker:ultimate_ingot_left_down>, [<ore:ingotDuraluminium>, <ore:ingotEnergeticSilver>, <ore:ingotBrass>, <ore:ingotRefinedObsidian>, <ore:ingotHSLASteel>, <ore:ingotThermoconducting>, <ore:ingotThaumiumTerra>, <ore:ingotMoonstone>, <ore:ingotUnsweetenedChocolate>, <ore:ingotLithiumManganeseDioxide>, <ore:ingotZircaloy>, <ore:ingotInvar>, <ore:ingotAlumite>, <ore:ingotMagnesiumDiboride>, <ore:ingotElectricalSteel>, <ore:ingotTough>, <ore:ingotManganeseOxide>, <ore:ingotCerulean>, <ore:ingotEndSteel>, <ore:ingotEnchantedMetal>, <ore:ingotUranium>, <ore:ingotEnrichedGold>, <ore:ingotOvium>, <ore:ingotExtreme>, <ore:ingotCold>, <extendedcrafting:material:36>, <ore:ingotAether>, <ore:ingotHardCarbon>, <ore:ingotBrickNetherGlazed>, <ore:ingotManasteel>, <ore:ingotRedstoneAlloy>, <ore:ingotAstralStarmetal>, <ore:ingotZirconiumMolybdenum>, <ore:ingotKnightmetal>, <ore:ingotSteeleaf>, <ore:ingotTerrasteel>, <ore:ingotMagnet>, <ore:ingotDawnstone>, <ore:ingotCrudeSteel>, <ore:ingotConstructionAlloy>, <ore:ingotRefinedGlowstone>, <ore:ingotTungstenCarbide>, <ore:ingotNiobiumTin>, <ore:ingotBasalt>, <ore:ingotDyonite>, <ore:ingotObsidiorite>, <ore:ingotSentientMetal>, <ore:ingotArdite>, <ore:ingotKnightslime>, <ore:ingotTiberium>, <ore:ingotSeismum>, <ore:ingotTerrax>, <ore:ingotChrome>, <ore:ingotTritonite>, <ore:ingotJauxum>, <ore:ingotNihilite>, <ore:ingotPlutonium>, <ore:listAllmeatcooked>, <ore:listAllmeatraw>, <ore:ingotManyullyn>, <ore:ingotBronze>, <ore:ingotWyvernMetal>, <ore:ingotNiob>, <ore:ingotEezo>, <ore:ingot_dark_soularium>, <ore:ingotBoundMetal>, <ore:ingotUru>, <ore:ingotCobalt>, <ore:ingotAlubrass>, <ore:ingotKarmesine>, <ore:ingotStrontium>, <ore:ingotSignalum>, <ore:ingotYrdeen>, <ore:ingotDraconium>, <ore:ingotMirion>, <ore:ingotCalcium>, <ore:ingotPrometheum>, <ore:ingotOsmiridium>, <ore:ingotDuranite>, <ore:ingotDilithium>, <ore:ingotIronCompressed>]);
mods.extendedcrafting.TableCrafting.addShapeless(4, <contenttweaker:ultimate_ingot_right_up>, [<ore:ingotMercury>, <ore:ingotBloodInfusedIron>, <ore:ingotNiob>, <ore:ingotAstrium>, <ore:ingotMeteorite>, <ore:ingotStainlessSteel>, <ore:ingotTitanium>, <ore:ingotFerroboron>, <ore:ingotSodium>, <ore:ingotAntimony>, <ore:ingotImperomite>, <ore:ingotIgnitz>, <ore:ingotFractum>, <ore:ingotGelidEnderium>, <ore:ingotPsi>, <ore:ingotElectrotineAlloy>, <ore:ingotElectrumFlux>, <ore:ingotNichrome>, <ore:ingotNiobiumTitanium>, <ore:ingotHafnium>, <ore:ingotPotassium>, <calculator:reinforcedironingot>, <ore:ingotRedAlloy>, <ore:ingotNeodymium>, <ore:ingotIvoryPsi>, <ore:ingotEbonyPsi>, <ore:ingotYttrium>, <ore:ingotAbyssum>, <ore:ingotIox>, <ore:ingotTriberium>, <ore:ingotPigiron>, <ore:ingotProxii>, <ore:ingotAurorium>, <ore:ingotBloodBronze>, <ore:ingotTungsten>, <ore:ingotAdamant>, <ore:gemTanzanite>, <ore:gemGoldenAmber>, <ore:crystalEmeraldic>, <ore:crystalIonite>, <ore:crystalKyronite>, <ore:itemEnderCrystal>, <ore:itemVibrantCrystal>, <ore:crystalLitherite>, <ore:gemRedGarnet>, <ore:slimecrystalPink>, <ore:gemRuby>, <ore:gemAquamarine>, <ore:gemFluorite>, <ore:gemFluorite>, <ore:gemApatite>, <ore:crystalPladium>, <ore:crystalEnori>, <ore:gemYellowGarnet>, <ore:gemRedstone>, <ore:gemRhodochrosite>, <ore:gemAmber>, <ore:slimecrystal>, <ore:slimecrystalSwet>, <ore:clathrateRedstone>, <ore:clathrateEnder>, <ore:crystalCrudeOil>, <ore:crystalCinnabar>, <ore:gemPsi>, <ore:gemCrystalFlux>, <ore:gemCoal>, <ore:gemDimensionalShard>, <ore:gemPhosphorus>, <ore:crystalLonsdaleite>, <ore:gemZanite>, <ore:slimecrystal>, <ore:crystalSlagRich>, <ore:gemAmbrosium>, <ore:itemPulsatingCrystal>, <ore:gemDiamondFake>, <ore:crystalRestonia>, <ore:crystalPalis>, <ore:crystalCertusQuartz>, <ore:gemQuartzBlack>, <ore:gemBoronArsenide>, <ore:slimecrystalMagma>]);
mods.extendedcrafting.TableCrafting.addShapeless(4, <contenttweaker:ultimate_ingot_right_down>, [<ore:gemAmethyst>, <ore:clathrateGlowstone>, <ore:gemEmerald>, <ore:gemQuartz>, <ore:crystalFluix>, <ore:gemAether>, <ore:crystalAethium>, <ore:itemPrecientCrystal>, <ore:craftingIndustrialDiamond>, <ore:crystalDiamantine>, <ore:gemVilliaumite>, <ore:gemCarobbiite>, <ore:itemWeatherCrystal>, <ore:crystalVoid>, <ore:crystalErodium>, <ore:gemLapis>, <ore:gemPeridot>, <ore:gemSapphire>, <ore:gemSapphire>, <ore:gemBoronNitride>, <ore:gemGelid>, <ore:crystalSlag>, <ore:ingotPrimordial>, <ore:ingotCrystalMatrix>, <ore:ingotGallium>, <ore:ingotSemiconductor>, <ore:ingotUUMatter>, <ore:ingotNyx>, <ore:ingotDraconicMetal>, <ore:ingotTungstensteel>, <ore:ingotCrystaltine>, <ore:ingotCrystallinePinkSlime>, <ore:ingotStellarAlloy>, <ore:ingotMelodicAlloy>, <ore:ingotCrystallineAlloy>, <ore:ingotMystic>, <ore:ingotSuperconduct>, <ore:ingotDraconiumAwakened>, <ore:ingotVibranium>, <ore:ingotVoid>, <extendedcrafting:material:48>, <ore:ingotSupremium>, <ore:ingotOsgloglas>, <ore:ingotSuperAlloy>, <ore:ingotLumix>, <ore:ingotNucleum>, <ore:ingotSolarium>, <ore:ingotMithminite>, <ore:ingotAurorianSteel>, <ore:ingotValkyrie>, <ore:gaiaIngot>, <ore:ingotMithrillium>, <ore:ingotAdaminite>, <ore:ingotChaoticMetal>, <ore:ingotGaiasteel>, <ore:ingotCosmicNeutronium>, <ore:ingotInsanium>, <bloodarsenal:base_item:3>, <bloodmagic:item_demon_crystal>, <bloodmagic:item_demon_crystal:1>, <bloodmagic:item_demon_crystal:2>, <bloodmagic:item_demon_crystal:3>, <bloodmagic:item_demon_crystal:4>, <astralsorcery:itemcraftingcomponent:4>, <ore:ingotBrickSeared>, <tconstruct:materials:1>, <tconstruct:materials:2>, <tconstruct:materials:16>, <tcomplement:materials:1>, <ore:dustMana>, <ore:dustPetrotheum>, <ore:dustAerotheum>, <ore:dustCryotheum>, <ore:dustPyrotheum>, <theaurorian:crystal>, <theaurorian:crystallineingot>, <theaurorian:aurorianiteingot>, <theaurorian:umbraingot>, <ore:ingotBrick>, <ore:ingotBrickNether>, <calculator:redstoneingot>]);

mods.extendedcrafting.TableCrafting.addShaped(4, <extendedcrafting:storage:4>, [
	[<contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <ore:circuitUniversal>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>], 
	[<contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <ore:circuitUniversal>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>], 
	[<contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <ore:circuitUniversal>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>], 
	[<contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <contenttweaker:ultimate_ingot_left_up>, <ore:circuitUniversal>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>, <contenttweaker:ultimate_ingot_right_up>], 
	[<ore:circuitUniversal>, <ore:circuitUniversal>, <ore:circuitUniversal>, <ore:circuitUniversal>, <ore:circuitUniversal>, <ore:circuitUniversal>, <ore:circuitUniversal>, <ore:circuitUniversal>, <ore:circuitUniversal>], 
	[<contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <ore:circuitUniversal>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>], 
	[<contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <ore:circuitUniversal>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>], 
	[<contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <ore:circuitUniversal>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>], 
	[<contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <contenttweaker:ultimate_ingot_left_down>, <ore:circuitUniversal>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>, <contenttweaker:ultimate_ingot_right_down>]
]);
