
mods.extendedcrafting.TableCrafting.addShaped(4, <auraddons:item_creative_aura_cache>, [
	[null, null, null, <auraddons:block_aura_transporter>, <auraddons:block_aura_transporter>, <auraddons:block_aura_transporter>, null, null, null], 
	[null, null, <auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:aura_detector>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>, null, null], 
	[null, <auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:field_creator>, <naturesaura:field_creator>, <naturesaura:field_creator>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>, null], 
	[<auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:field_creator>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:field_creator>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>], 
	[<auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:field_creator>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:field_creator>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>], 
	[<auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:field_creator>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:aura_trove>, <naturesaura:field_creator>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>], 
	[null, <auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:field_creator>, <naturesaura:field_creator>, <naturesaura:field_creator>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>, null], 
	[null, null, <auraddons:block_aura_transporter>, <naturesaura:aura_detector>, <naturesaura:aura_detector>, <naturesaura:aura_detector>, <auraddons:block_aura_transporter>, null, null], 
	[null, null, null, <auraddons:block_aura_transporter>, <auraddons:block_aura_transporter>, <auraddons:block_aura_transporter>, null, null, null]
]);
mods.extendedcrafting.TableCrafting.addShaped(4, <bloodmagic:activation_crystal:2>, [
	[<bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <ore:blockBloodInfusedIron>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <ore:blockBloodInfusedIron>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <bloodarsenal:glass_dagger_of_sacrifice>, <ore:blockBloodInfusedIron>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <mysticalagriculture:soulium_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <ore:blockBloodInfusedIron>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <botania:enderdagger>, <botania:enderdagger>, <botania:enderdagger>, <ore:blockBloodInfusedIron>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <botania:enderdagger>, <botania:enderdagger>, <botania:enderdagger>, <ore:blockBloodInfusedIron>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <botania:enderdagger>, <botania:enderdagger>, <botania:enderdagger>, <ore:blockBloodInfusedIron>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodarsenal:glass_sacrificial_dagger>, <bloodmagic:activation_crystal:1>], 
	[<bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>, <bloodmagic:activation_crystal:1>]
]);

mods.extendedcrafting.TableCrafting.addShaped(4, <tinkertoolcasts:cast_creative>, [
	[<ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:1>, <tinkertoolcasts:cast_ultimate:1>, <tinkertoolcasts:cast_ultimate:1>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate:2>, <tinkertoolcasts:cast_ultimate:2>, <tinkertoolcasts:cast_ultimate:2>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:1>, <tinkertoolcasts:upgrade_advanced>, <tinkertoolcasts:upgrade_advanced>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:upgrade_reinforced>, <tinkertoolcasts:upgrade_reinforced>, <tinkertoolcasts:cast_ultimate:2>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:1>, <tinkertoolcasts:upgrade_advanced>, <tinkertoolcasts:upgrade_advanced>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:upgrade_reinforced>, <tinkertoolcasts:upgrade_reinforced>, <tinkertoolcasts:cast_ultimate:2>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:3>, <tinkertoolcasts:upgrade_iridium>, <tinkertoolcasts:upgrade_iridium>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:upgrade_ultimate>, <tinkertoolcasts:upgrade_ultimate>, <tinkertoolcasts:cast_ultimate:4>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:3>, <tinkertoolcasts:upgrade_iridium>, <tinkertoolcasts:upgrade_iridium>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:upgrade_ultimate>, <tinkertoolcasts:upgrade_ultimate>, <tinkertoolcasts:cast_ultimate:4>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <tinkertoolcasts:cast_ultimate:3>, <tinkertoolcasts:cast_ultimate:3>, <tinkertoolcasts:cast_ultimate:3>, <tinkertoolcasts:cast_ultimate>, <tinkertoolcasts:cast_ultimate:4>, <tinkertoolcasts:cast_ultimate:4>, <tinkertoolcasts:cast_ultimate:4>, <ore:blockUUMatter>], 
	[<ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>, <ore:blockUUMatter>]
]);

mods.extendedcrafting.TableCrafting.addShaped(4, <thaumicwonders:creative_essentia_jar>, [
	[<thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumicenergistics:essentia_component_64k>, <thaumicrestoration:block_crystal>, <avaritia:resource:5>, <thaumicrestoration:block_crystal>, <thaumicenergistics:essentia_component_64k>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumicenergistics:essentia_component_64k>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <thaumicenergistics:essentia_component_64k>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumicenergistics:essentia_component_64k>, <thaumicrestoration:block_crystal>, <avaritia:resource:5>, <thaumicrestoration:block_crystal>, <thaumicenergistics:essentia_component_64k>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumicenergistics:essentia_component_64k>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumictinkerer:ichor_block>, <thaumadditions:jar_mithminite>], 
	[<thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>, <thaumadditions:jar_mithminite>]
]);

mods.extendedcrafting.TableCrafting.addShaped(4, <wct:wct_creative>, [
	[<ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wct:wct>, <wct:wct>, <wct:wct>, <wct:magnet_card>, <wft:wft>, <wft:wft>, <wft:wft>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wct:wct>, <wct:wct>, <wct:wct>, <wct:magnet_card>, <wft:wft>, <wft:wft>, <wft:wft>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wct:wct>, <wct:wct>, <wct:wct>, <wct:magnet_card>, <wft:wft>, <wft:wft>, <wft:wft>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wct:magnet_card>, <wct:magnet_card>, <wct:magnet_card>, <wct:magnet_card>, <wct:magnet_card>, <wct:magnet_card>, <wct:magnet_card>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wit:wit>, <wit:wit>, <wit:wit>, <wct:magnet_card>, <wpt:wpt>, <wpt:wpt>, <wpt:wpt>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wit:wit>, <wit:wit>, <wit:wit>, <wct:magnet_card>, <wpt:wpt>, <wpt:wpt>, <wpt:wpt>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <wit:wit>, <wit:wit>, <wit:wit>, <wct:magnet_card>, <wpt:wpt>, <wpt:wpt>, <wpt:wpt>, <ae2wtlib:wut>], 
	[<ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>, <ae2wtlib:wut>]
]);

mods.extendedcrafting.TableCrafting.addShaped(4, <reactorbuilder:creativereactorbuilder>, [
	[<nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_glass>, <draconicevolution:reactor_component>, <draconicevolution:reactor_component>, <draconicevolution:reactor_component>, <nuclearcraft:fission_glass>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_glass>, <draconicevolution:reactor_component>, <draconicadditions:chaos_stabilizer_core>, <draconicevolution:reactor_component>, <nuclearcraft:fission_glass>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_glass>, <draconicevolution:reactor_component>, <draconicevolution:reactor_component>, <draconicevolution:reactor_component>, <nuclearcraft:fission_glass>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <nuclearcraft:fission_glass>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <reactorbuilder:reactorbuilder>, <nuclearcraft:fission_casing>], 
	[<nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>, <nuclearcraft:fission_casing>]
]);

mods.extendedcrafting.TableCrafting.addShaped(4, <equivalentenergistics:emc_cell_creative>, [
	[<ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_crafter:3>, <equivalentenergistics:emc_crafter:3>, <equivalentenergistics:emc_crafter:3>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_crafter:3>, <equivalentenergistics:emc_crafter:3>, <equivalentenergistics:emc_crafter:3>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <equivalentenergistics:emc_storage_component:7>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_condenser:3>, <equivalentenergistics:emc_condenser:3>, <equivalentenergistics:emc_condenser:3>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <projecte:collector_mk3>, <projecte:collector_mk3>, <equivalentenergistics:emc_condenser:3>, <equivalentenergistics:emc_condenser:3>, <equivalentenergistics:emc_condenser:3>, <projecte:relay_mk3>, <projecte:relay_mk3>, <ore:blockRedMatter>], 
	[<ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>, <ore:blockRedMatter>]
]);